# Generated by Django 4.1.7 on 2023-02-16 20:50

import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(db_index=True, max_length=35)),
                ('seccion', models.CharField(db_index=True, max_length=30)),
                ('precio', models.IntegerField()),
                ('imagen_url', models.TextField()),
                ('descripcion', models.TextField()),
                ('descuento', models.IntegerField(db_index=True, default=0)),
                ('calificacion', models.IntegerField(db_index=True, default=0)),
                ('unidades', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('codigo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('last_login', models.DateTimeField(default=datetime.datetime.now)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('codigo_resena', models.AutoField(primary_key=True, serialize=False)),
                ('resena_titulo', models.CharField(max_length=45)),
                ('resena_texto', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('fecha_resena', models.DateField(default='2023-02-16')),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.producto')),
                ('codigo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('codigo_favorito', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.producto')),
                ('codigo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('codigo_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.producto')),
                ('codigo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
